### ISSUE TITLE
variable name could be improved

### ISSUE THREAD

**Issue by kirjavascript** [sector-f/failoverd#5]
https://github.com/sector-f/failoverd/blob/672ed3011898df9287a34ca04b264988bc411f2b/main.go#L27

I suggest 'pinger' please let me know what you think thanks

**Comment by sector-f** [comment]
Per [Practical Go](https://dave.cheney.net/practical-go/presentations/gophercon-israel.html#_the_larger_the_identifiers_scope_the_larger_its_name), "Short variable names work well when the distance between their declaration and last use is short."

Given that `p` is the primary focus of the `main` function, and that the `main` function is not very long, I am not convinced that the proposed change would actually improve readability.

**Comment by kirjavascript** [comment]
fair!
